""" Function that counts number of nucleotide bases (A,T,C,G) in a DNA sequence"""

seq = 'CTTCAATATGTTTTAATGCTTCTGATGAAGGCTGTTATTGCTTATAAACAATCCAAGCTCAAGACGCTGCGAACGTAAACCGGATTCTTCAGACGCTAAAATTGATGACGAGCCTGATAACGTCCACGGCTAACAACGGGTGGCCATAATGTCTGGGCGTTCCCGCATACAATGTCGGCATTACCCAGGGAACGGTGTTTGGCGCTGTTGCTAACCCAGAGACGCCAGACACTAACACGCTTCTAAACGCTGAAAGGAGTATTTCGCTGTAGGCACCTGGACAGGTTGTCGATATTGTTGCGAGTCTGATAGAGAAGACAGCTATGGGGTAACTCCAGGCACGAACAAATGCCAACTAGATGTGGGCCGGAATTCTACGGACAGCACGCCGCTGCGTGGACATGGTTACAGTGAGCTACGACATTGCCATGAGGACACCAGTTTTTGCAAATGTCGGATCAACCTCCATCCAAAACACGCAAAAAGCAGACGCCGCGTACCGCGCCACTATGCCTTTCTCTTTGCTATCGGGTGCTGAGTGCATTTGCACGATTTTGTGGGTTCGTACGTGGATCCGGTTAGAGACCATCATACTACTATCCGCGAGAGCTCTCGAATGCTACGATAAGGACCTCTATTCATATATTGAAAGGTATAACTGTACCTCTAAATTGCTCCCTGGTAAGACTAGATTACTAGGCTTCCACGCTCATGACTTGTACACCACAGCCTTGTCGGTCTTATCCGACCACCCCTCCTCTTGTATGAAGGCCTCTCCTCCAGCCACACCAAGGTCAATGTTGCTTCATAGATGCTACTTGAAATTGTCGCCGTGACCAGTATCAACAGAAAGGCTGTA'

def CountFreq(seq):
    tempdata = {'A':0,'C':0,'G':0,'T':0}
    for nuc in seq:
        tempdata[nuc] += 1
    return tempdata

result = CountFreq(seq)
print(' '.join([str(val) for key,val in result.items()]))